const webData = {
  industryCategory: [
    '批發、零售、傳直銷業',
    '文教相關業',
    '大眾傳播相關業',
    '旅遊、休閒、運動業',
    '一般服務業',
    '電子資訊、軟體、半導體相關業',
    '一般製造業',
    '農林漁牧水電資源業',
    '運輸物流及倉儲',
    '政治宗教及社福相關業',
    '金融投顧及保險業',
    '法律、會計、顧問、研發、設計業',
    '建築營造及不動產相關業',
    '醫療保健及環境衛生業',
    '礦業及土石採取業',
    '住宿、餐飲服務業',
  ],
  jobCategory: [
    '經營、人資類',
    '行政、總務、法務類',
    '財會、金融專業類',
    '行銷、企劃、專案管理類',
    '客服、門市、業務、貿易類',
    '餐飲、旅遊、美容美髮類',
    '資訊軟體系統類',
    '操作、技術、維修類',
    '資材、物流、運輸類',
    '營建、製圖類',
    '傳播藝術、設計類',
    '文字、傳媒類',
    '醫療、保健服務類',
    '學術、教育、輔導類',
    '研發類',
    '生產製造、品管、環衛類',
    '軍警消、保全類',
    '其他類',
  ],
  city: [
    '基隆市',
    '台北市',
    '新北市',
    '桃園市',
    '新竹縣',
    '新竹市',
    '苗栗縣',
    '台中市',
    '彰化市',
    '南投縣',
    '雲林縣',
    '嘉義縣',
    '台南市',
    '台南市',
    '屏東縣',
    '宜蘭縣',
  ],
  education: ['不限', '高中職', '大學', '碩士', '博士'],
  candidateEducation: ['國中小', '高中職', '大學', '碩士', '博士'],
  workExp: ['不限', '一年以下', '1~3年', '3~5年', '5年以上'],
  candidateWorkExp: ['無工作經驗', '一年以下', '1~3年', '3~5年', '5年以上'],
  dataWorkTime: ['日班', '夜班', '假日班'],
  dataWorkType: ['全職', '兼職', '實習'],
  workTime: [
    { title: '日班', select: false },
    { title: '夜班', select: false },
    { title: '假日班', select: false },
  ],
  workType: [
    { title: '全職', select: false },
    { title: '兼職', select: false },
    { title: '實習', select: false },
  ],
  // 縣市
  cities: [
    '台北市',
    '基隆市',
    '新北市',
    '宜蘭縣',
    '桃園市',
    '新竹市',
    '新竹縣',
    '苗栗縣',
    '台中市',
    '彰化縣',
    '南投縣',
    '嘉義市',
    '嘉義縣',
    '雲林縣',
    '台南市',
    '高雄市',
    '澎湖縣',
    '金門縣',
    '屏東縣',
    '台東縣',
    '花蓮縣',
    '連江縣',
  ],
  // 區域
  districts: {
    // 台北市
    台北市: {
      district: [
        '中正區',
        '大同區',
        '中山區',
        '松山區',
        '大安區',
        '萬華區',
        '信義區',
        '士林區',
        '北投區',
        '內湖區',
        '南港區',
        '文山區',
      ],
      code: ['100', '103', '104', '105', '106', '108', '110', '111', '112', '114', '115', '116'],
    },
    基隆市: {
      district: ['仁愛區', '信義區', '中正區', '中山區', '安樂區', '暖暖區', '七堵區'],

      code: ['200', '201', '202', '203', '204', '205', '206'],
    },
    新北市: {
      district: [
        '萬里區',
        '金山區',
        '板橋區',
        '汐止區',
        '深坑區',
        '石碇區',
        '瑞芳區',
        '平溪區',
        '雙溪區',
        '貢寮區',
        '新店區',
        '坪林區',
        '烏來區',
        '永和區',
        '中和區',
        '土城區',
        '三峽區',
        '樹林區',
        '鶯歌區',
        '三重區',
        '新莊區',
        '泰山區',
        '林口區',
        '蘆洲區',
        '五股區',
        '八里區',
        '淡水區',
        '三芝區',
        '石門區',
      ],

      code: [
        '207',
        '208',
        '220',
        '221',
        '222',
        '223',
        '224',
        '226',
        '227',
        '228',
        '231',
        '232',
        '233',
        '234',
        '235',
        '236',
        '237',
        '238',
        '239',
        '241',
        '242',
        '243',
        '244',
        '247',
        '248',
        '249',
        '251',
        '252',
        '253',
      ],
    },
    宜蘭縣: {
      district: [
        '宜蘭市',
        '頭城鎮',
        '礁溪鄉',
        '壯圍鄉',
        '員山鄉',
        '羅東鎮',
        '三星鄉',
        '大同鄉',
        '五結鄉',
        '冬山鄉',
        '蘇澳鎮',
        '南澳鄉',
        '釣魚台列嶼',
      ],

      code: [
        '260',
        '261',
        '262',
        '263',
        '264',
        '265',
        '266',
        '267',
        '268',
        '269',
        '270',
        '272',
        '290',
      ],
    },
    桃園市: {
      district: [
        '中壢區',
        '平鎮區',
        '龍潭區',
        '楊梅區',
        '新屋區',
        '觀音區',
        '桃園區',
        '龜山區',
        '八德區',
        '大溪區',
        '復興區',
        '大園區',
        '蘆竹區',
      ],
      code: [
        '320',
        '324',
        '325',
        '326',
        '327',
        '328',
        '330',
        '333',
        '334',
        '335',
        '336',
        '337',
        '338',
      ],
    },
    新竹市: {
      district: ['東區', '北區', '香山區'],
      code: ['300', '300', '300'],
    },
    新竹縣: {
      district: [
        '竹北市',
        '湖口鄉',
        '新豐鄉',
        '新埔鎮',
        '關西鎮',
        '芎林鄉',
        '寶山鄉',
        '竹東鎮',
        '五峰鄉',
        '橫山鄉',
        '尖石鄉',
        '北埔鄉',
        '峨眉鄉',
      ],
      code: [
        '302',
        '303',
        '304',
        '305',
        '306',
        '307',
        '308',
        '310',
        '311',
        '312',
        '313',
        '314',
        '315',
      ],
    },
    苗栗縣: {
      district: [
        '竹南鎮',
        '頭份市',
        '三灣鄉',
        '南庄鄉',
        '獅潭鄉',
        '後龍鎮',
        '通霄鎮',
        '苑裡鎮',
        '苗栗市',
        '造橋鄉',
        '頭屋鄉',
        '公館鄉',
        '大湖鄉',
        '泰安鄉',
        '銅鑼鄉',
        '三義鄉',
        '西湖鄉',
        '卓蘭鎮',
      ],
      code: [
        '350',
        '351',
        '352',
        '353',
        '354',
        '356',
        '357',
        '358',
        '360',
        '361',
        '362',
        '363',
        '364',
        '365',
        '366',
        '367',
        '368',
        '369',
      ],
    },
    台中市: {
      district: [
        '中區',
        '東區',
        '南區',
        '西區',
        '北區',
        '北屯區',
        '西屯區',
        '南屯區',
        '太平區',
        '大里區',
        '霧峰區',
        '烏日區',
        '豐原區',
        '后里區',
        '石岡區',
        '東勢區',
        '和平區',
        '新社區',
        '潭子區',
        '大雅區',
        '神岡區',
        '大肚區',
        '沙鹿區',
        '龍井區',
        '梧棲區',
        '清水區',
        '大甲區',
        '外埔區',
        '大安區',
      ],
      code: [
        '400',
        '401',
        '402',
        '403',
        '404',
        '406',
        '407',
        '408',
        '411',
        '412',
        '413',
        '414',
        '420',
        '421',
        '422',
        '423',
        '424',
        '426',
        '427',
        '428',
        '429',
        '432',
        '433',
        '434',
        '435',
        '436',
        '437',
        '438',
        '439',
      ],
    },
    彰化縣: {
      district: [
        '彰化市',
        '芬園鄉',
        '花壇鄉',
        '秀水鄉',
        '鹿港鎮',
        '福興鄉',
        '線西鄉',
        '和美鎮',
        '伸港鄉',
        '員林市',
        '社頭鄉',
        '永靖鄉',
        '埔心鄉',
        '溪湖鎮',
        '大村鄉',
        '埔鹽鄉',
        '田中鎮',
        '北斗鎮',
        '田尾鄉',
        '埤頭鄉',
        '溪州鄉',
        '竹塘鄉',
        '二林鎮',
        '大城鄉',
        '芳苑鄉',
        '二水鄉',
      ],
      code: [
        '500',
        '502',
        '503',
        '504',
        '505',
        '506',
        '507',
        '508',
        '509',
        '510',
        '511',
        '512',
        '513',
        '514',
        '515',
        '516',
        '520',
        '521',
        '522',
        '523',
        '524',
        '525',
        '526',
        '527',
        '528',
        '530',
      ],
    },
    南投縣: {
      district: [
        '南投市',
        '中寮鄉',
        '草屯鎮',
        '國姓鄉',
        '埔里鎮',
        '仁愛鄉',
        '名間鄉',
        '集集鎮',
        '水里鄉',
        '魚池鄉',
        '信義鄉',
        '竹山鎮',
        '鹿谷鄉',
      ],
      code: [
        '540',
        '541',
        '542',
        '544',
        '545',
        '546',
        '551',
        '552',
        '553',
        '555',
        '556',
        '557',
        '558',
      ],
    },
    嘉義市: {
      district: ['東區', '西區'],
      code: ['600', '600'],
    },
    嘉義縣: {
      district: [
        '番路鄉',
        '梅山鄉',
        '竹崎鄉',
        '阿里山',
        '中埔鄉',
        '大埔鄉',
        '水上鄉',
        '鹿草鄉',
        '太保市',
        '朴子市',
        '東石鄉',
        '六腳鄉',
        '新港鄉',
        '民雄鄉',
        '大林鎮',
        '溪口鄉',
        '義竹鄉',
        '布袋鎮',
      ],
      code: [
        '602',
        '603',
        '604',
        '605',
        '606',
        '607',
        '608',
        '611',
        '612',
        '613',
        '614',
        '615',
        '616',
        '621',
        '622',
        '623',
        '624',
        '625',
      ],
    },
    雲林縣: {
      district: [
        '斗南鎮',
        '大埤鄉',
        '虎尾鎮',
        '土庫鎮',
        '褒忠鄉',
        '東勢鄉',
        '台西鄉',
        '崙背鄉',
        '麥寮鄉',
        '斗六市',
        '林內鄉',
        '古坑鄉',
        '莿桐鄉',
        '西螺鎮',
        '二崙鄉',
        '北港鎮',
        '水林鄉',
        '口湖鄉',
        '四湖鄉',
        '元長鄉',
      ],
      code: [
        '630',
        '631',
        '632',
        '633',
        '634',
        '635',
        '636',
        '637',
        '638',
        '640',
        '643',
        '646',
        '647',
        '648',
        '649',
        '651',
        '652',
        '653',
        '654',
        '655',
      ],
    },
    台南市: {
      district: [
        '中西區',
        '東區',
        '南區',
        '北區',
        '安平區',
        '安南區',
        '永康區',
        '歸仁區',
        '新化區',
        '左鎮區',
        '玉井區',
        '楠西區',
        '南化區',
        '仁德區',
        '關廟區',
        '龍崎區',
        '官田區',
        '麻豆區',
        '佳里區',
        '西港區',
        '七股區',
        '將軍區',
        '學甲區',
        '北門區',
        '新營區',
        '後壁區',
        '白河區',
        '東山區',
        '六甲區',
        '下營區',
        '柳營區',
        '鹽水區',
        '善化區',
        '大內區',
        '山上區',
        '新市區',
        '安定區',
      ],
      code: [
        '700',
        '701',
        '702',
        '704',
        '708',
        '709',
        '710',
        '711',
        '712',
        '713',
        '714',
        '715',
        '716',
        '717',
        '718',
        '719',
        '720',
        '721',
        '722',
        '723',
        '724',
        '725',
        '726',
        '727',
        '730',
        '731',
        '732',
        '733',
        '734',
        '735',
        '736',
        '737',
        '741',
        '742',
        '743',
        '744',
        '745',
      ],
    },
    高雄市: {
      district: [
        '新興區',
        '前金區',
        '苓雅區',
        '鹽埕區',
        '鼓山區',
        '旗津區',
        '前鎮區',
        '三民區',
        '楠梓區',
        '小港區',
        '左營區',
        '仁武區',
        '大社區',
        '東沙群島',
        '南沙群島',
        '岡山區',
        '路竹區',
        '阿蓮區',
        '田寮區',
        '燕巢區',
        '橋頭區',
        '梓官區',
        '彌陀區',
        '永安區',
        '湖內區',
        '鳳山區',
        '大寮區',
        '林園區',
        '鳥松區',
        '大樹區',
        '旗山區',
        '美濃區',
        '六龜區',
        '內門區',
        '杉林區',
        '甲仙區',
        '桃源區',
        '那瑪夏區',
        '茂林區',
        '茄萣區',
      ],
      code: [
        '800',
        '801',
        '802',
        '803',
        '804',
        '805',
        '806',
        '807',
        '811',
        '812',
        '813',
        '814',
        '815',
        '817',
        '819',
        '820',
        '821',
        '822',
        '823',
        '824',
        '825',
        '826',
        '827',
        '828',
        '829',
        '830',
        '831',
        '832',
        '833',
        '840',
        '842',
        '843',
        '844',
        '845',
        '846',
        '847',
        '848',
        '849',
        '851',
        '852',
      ],
    },
    澎湖縣: {
      district: ['馬公市', '西嶼鄉', '望安鄉', '七美鄉', '白沙鄉', '湖西鄉'],
      code: ['880', '881', '882', '883', '884', '885'],
    },
    金門縣: {
      district: ['金沙鎮', '金湖鎮', '金寧鄉', '金城鎮', '烈嶼鄉', '烏坵鄉'],
      code: ['890', '891', '892', '893', '894', '896'],
    },
    屏東縣: {
      district: [
        '屏東市',
        '三地門鄉',
        '霧台鄉',
        '瑪家鄉',
        '九如鄉',
        '里港鄉',
        '高樹鄉',
        '鹽埔鄉',
        '長治鄉',
        '麟洛鄉',
        '竹田鄉',
        '內埔鄉',
        '萬丹鄉',
        '潮州鎮',
        '泰武鄉',
        '來義鄉',
        '萬巒鄉',
        '崁頂鄉',
        '新埤鄉',
        '南州鄉',
        '林邊鄉',
        '東港鎮',
        '琉球鄉',
        '佳冬鄉',
        '新園鄉',
        '枋寮鄉',
        '枋山鄉',
        '春日鄉',
        '獅子鄉',
        '車城鄉',
        '牡丹鄉',
        '恆春鎮',
        '滿州鄉',
      ],
      code: [
        '900',
        '901',
        '902',
        '903',
        '904',
        '905',
        '906',
        '907',
        '908',
        '909',
        '911',
        '912',
        '913',
        '920',
        '921',
        '922',
        '923',
        '924',
        '925',
        '926',
        '927',
        '928',
        '929',
        '931',
        '932',
        '940',
        '941',
        '942',
        '943',
        '944',
        '945',
        '946',
        '947',
      ],
    },
    台東縣: {
      district: [
        '台東市',
        '綠島鄉',
        '蘭嶼鄉',
        '延平鄉',
        '卑南鄉',
        '鹿野鄉',
        '關山鎮',
        '海端鄉',
        '池上鄉',
        '東河鄉',
        '成功鎮',
        '長濱鄉',
        '太麻里',
        '金峰鄉',
        '大武鄉',
        '達仁鄉',
      ],
      code: [
        '950',
        '951',
        '952',
        '953',
        '954',
        '955',
        '956',
        '957',
        '958',
        '959',
        '961',
        '962',
        '963',
        '964',
        '965',
        '966',
      ],
    },
    花蓮縣: {
      district: [
        '花蓮市',
        '新城鄉',
        '秀林鄉',
        '吉安鄉',
        '壽豐鄉',
        '鳳林鎮',
        '光復鄉',
        '豐濱鄉',
        '瑞穗鄉',
        '萬榮鄉',
        '玉里鎮',
        '卓溪鄉',
        '富里鄉',
      ],
      code: [
        '970',
        '971',
        '972',
        '973',
        '974',
        '975',
        '976',
        '977',
        '978',
        '979',
        '981',
        '982',
        '983',
      ],
    },
    連江縣: {
      district: ['南竿鄉', '北竿鄉', '莒光鄉', '東引鄉'],
      code: ['209', '210', '211', '212'],
    },
  },
  gender: ['男性', '女性'],
  skillLevel: ['略懂', '普通', '精通'],
  languages: [
    '中文',
    '英文',
    '日文',
    '韓文',
    '德文',
    '台語',
    '客語',
    '粵語',
    '西班牙文',
    '法文',
    '越南文',
    '泰文',
    '馬來文',
    '印尼文',
    '俄文',
    '義大利文',
    '阿拉伯文',
    '葡萄牙文',
    '菲律賓文',
  ],
  months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
  driverLicenses: [
    '輕型機車駕照',
    '普通重型機車駕照',
    '大型重型機車駕照',
    '普通小型車駕照',
    '普通大貨車駕照',
    '普通大客車駕照',
    '普通聯結車駕照',
    '職業小型車駕照',
    '職業大貨車駕照',
    '職業大客車駕照',
    '職業聯結車駕照',
  ],
  identity: ['外籍人士', '原住民', '二度就業', '身心障礙'],
  militaryService: ['役畢', '尚未服役', '免役', '等待入伍'],
  workPlace: [
    {
      cityName: '台北市',
      selectAll: false,
      district: [
        { distName: '中正區', select: false, code: '100' },
        { distName: '大同區', select: false, code: '103' },
        { distName: '中山區', select: false, code: '104' },
        { distName: '松山區', select: false, code: '105' },
        { distName: '大安區', select: false, code: '106' },
        { distName: '萬華區', select: false, code: '108' },
        { distName: '信義區', select: false, code: '110' },
        { distName: '士林區', select: false, code: '111' },
        { distName: '北投區', select: false, code: '112' },
        { distName: '內湖區', select: false, code: '114' },
        { distName: '南港區', select: false, code: '115' },
        { distName: '文山區', select: false, code: '116' },
      ],
    },
    {
      cityName: '基隆市',
      selectAll: false,
      district: [
        { distName: '仁愛區', select: false, code: '200' },
        { distName: '信義區', select: false, code: '201' },
        { distName: '中正區', select: false, code: '202' },
        { distName: '中山區', select: false, code: '203' },
        { distName: '安樂區', select: false, code: '204' },
        { distName: '暖暖區', select: false, code: '205' },
        { distName: '七堵區', select: false, code: '206' },
      ],
    },
    {
      cityName: '新北市',
      selectAll: false,
      district: [
        { distName: '萬里區', select: false, code: '207' },
        { distName: '金山區', select: false, code: '208' },
        { distName: '板橋區', select: false, code: '220' },
        { distName: '汐止區', select: false, code: '221' },
        { distName: '深坑區', select: false, code: '222' },
        { distName: '石碇區', select: false, code: '223' },
        { distName: '瑞芳區', select: false, code: '224' },
        { distName: '平溪區', select: false, code: '226' },
        { distName: '雙溪區', select: false, code: '227' },
        { distName: '貢寮區', select: false, code: '228' },
        { distName: '新店區', select: false, code: '231' },
        { distName: '坪林區', select: false, code: '232' },
        { distName: '烏來區', select: false, code: '233' },
        { distName: '永和區', select: false, code: '234' },
        { distName: '中和區', select: false, code: '235' },
        { distName: '土城區', select: false, code: '236' },
        { distName: '三峽區', select: false, code: '237' },
        { distName: '樹林區', select: false, code: '238' },
        { distName: '鶯歌區', select: false, code: '239' },
        { distName: '三重區', select: false, code: '241' },
        { distName: '新莊區', select: false, code: '242' },
        { distName: '泰山區', select: false, code: '243' },
        { distName: '林口區', select: false, code: '244' },
        { distName: '蘆洲區', select: false, code: '247' },
        { distName: '五股區', select: false, code: '248' },
        { distName: '八里區', select: false, code: '249' },
        { distName: '淡水區', select: false, code: '251' },
        { distName: '三芝區', select: false, code: '252' },
        { distName: '石門區', select: false, code: '253' },
      ],
    },
    {
      cityName: '宜蘭縣',
      selectAll: false,
      district: [
        { distName: '宜蘭市', select: false, code: '260' },
        { distName: '頭城鎮', select: false, code: '261' },
        { distName: '礁溪鄉', select: false, code: '262' },
        { distName: '壯圍鄉', select: false, code: '263' },
        { distName: '員山鄉', select: false, code: '264' },
        { distName: '羅東鎮', select: false, code: '265' },
        { distName: '三星鄉', select: false, code: '266' },
        { distName: '大同鄉', select: false, code: '267' },
        { distName: '五結鄉', select: false, code: '268' },
        { distName: '冬山鄉', select: false, code: '269' },
        { distName: '蘇澳鎮', select: false, code: '270' },
        { distName: '南澳鄉', select: false, code: '272' },
        { distName: '釣魚台列嶼', select: false, code: '290' },
      ],
    },
    {
      cityName: '新竹市',
      selectAll: false,
      district: [
        { distName: '東區', select: false, code: '300' },
        { distName: '北區', select: false, code: '300' },
        { distName: '香山區', select: false, code: '300' },
      ],
    },
    {
      cityName: '新竹縣',
      selectAll: false,
      district: [
        { distName: '竹北市', select: false, code: '302' },
        { distName: '湖口鄉', select: false, code: '303' },
        { distName: '新豐鄉', select: false, code: '304' },
        { distName: '新埔鎮', select: false, code: '305' },
        { distName: '關西鎮', select: false, code: '306' },
        { distName: '芎林鄉', select: false, code: '307' },
        { distName: '寶山鄉', select: false, code: '308' },
        { distName: '竹東鎮', select: false, code: '310' },
        { distName: '五峰鄉', select: false, code: '311' },
        { distName: '橫山鄉', select: false, code: '312' },
        { distName: '尖石鄉', select: false, code: '313' },
        { distName: '北埔鄉', select: false, code: '314' },
        { distName: '峨眉鄉', select: false, code: '315' },
      ],
    },
    {
      cityName: '桃園市',
      selectAll: false,
      district: [
        { distName: '中壢區', select: false, code: '320' },
        { distName: '平鎮區', select: false, code: '324' },
        { distName: '龍潭區', select: false, code: '325' },
        { distName: '楊梅區', select: false, code: '326' },
        { distName: '新屋區', select: false, code: '327' },
        { distName: '觀音區', select: false, code: '328' },
        { distName: '桃園區', select: false, code: '330' },
        { distName: '龜山區', select: false, code: '333' },
        { distName: '八德區', select: false, code: '334' },
        { distName: '大溪區', select: false, code: '335' },
        { distName: '復興區', select: false, code: '336' },
        { distName: '大園區', select: false, code: '337' },
        { distName: '蘆竹區', select: false, code: '338' },
      ],
    },
    {
      cityName: '苗栗縣',
      selectAll: false,
      district: [
        { distName: '竹南鎮', select: false, code: '350' },
        { distName: '頭份市', select: false, code: '351' },
        { distName: '三灣鄉', select: false, code: '352' },
        { distName: '南庄鄉', select: false, code: '353' },
        { distName: '獅潭鄉', select: false, code: '354' },
        { distName: '後龍鎮', select: false, code: '356' },
        { distName: '通霄鎮', select: false, code: '357' },
        { distName: '苑裡鎮', select: false, code: '358' },
        { distName: '苗栗市', select: false, code: '360' },
        { distName: '造橋鄉', select: false, code: '361' },
        { distName: '頭屋鄉', select: false, code: '362' },
        { distName: '公館鄉', select: false, code: '363' },
        { distName: '大湖鄉', select: false, code: '364' },
        { distName: '泰安鄉', select: false, code: '365' },
        { distName: '銅鑼鄉', select: false, code: '366' },
        { distName: '三義鄉', select: false, code: '367' },
        { distName: '西湖鄉', select: false, code: '368' },
        { distName: '卓蘭鎮', select: false, code: '369' },
      ],
    },
    {
      cityName: '台中市',
      selectAll: false,
      district: [
        { distName: '中區', select: false, code: '400' },
        { distName: '東區', select: false, code: '401' },
        { distName: '南區', select: false, code: '402' },
        { distName: '西區', select: false, code: '403' },
        { distName: '北區', select: false, code: '404' },
        { distName: '北屯區', select: false, code: '406' },
        { distName: '西屯區', select: false, code: '407' },
        { distName: '南屯區', select: false, code: '408' },
        { distName: '太平區', select: false, code: '411' },
        { distName: '大里區', select: false, code: '412' },
        { distName: '霧峰區', select: false, code: '413' },
        { distName: '烏日區', select: false, code: '414' },
        { distName: '豐原區', select: false, code: '420' },
        { distName: '后里區', select: false, code: '421' },
        { distName: '石岡區', select: false, code: '422' },
        { distName: '東勢區', select: false, code: '423' },
        { distName: '和平區', select: false, code: '424' },
        { distName: '新社區', select: false, code: '426' },
        { distName: '潭子區', select: false, code: '427' },
        { distName: '大雅區', select: false, code: '428' },
        { distName: '神岡區', select: false, code: '429' },
        { distName: '大肚區', select: false, code: '432' },
        { distName: '沙鹿區', select: false, code: '433' },
        { distName: '龍井區', select: false, code: '434' },
        { distName: '梧棲區', select: false, code: '435' },
        { distName: '清水區', select: false, code: '436' },
        { distName: '大甲區', select: false, code: '437' },
        { distName: '外埔區', select: false, code: '438' },
        { distName: '大安區', select: false, code: '439' },
      ],
    },
    {
      cityName: '彰化縣',
      selectAll: false,
      district: [
        { distName: '彰化市', select: false, code: '500' },
        { distName: '芬園鄉', select: false, code: '502' },
        { distName: '花壇鄉', select: false, code: '503' },
        { distName: '秀水鄉', select: false, code: '504' },
        { distName: '鹿港鎮', select: false, code: '505' },
        { distName: '福興鄉', select: false, code: '506' },
        { distName: '線西鄉', select: false, code: '507' },
        { distName: '和美鎮', select: false, code: '508' },
        { distName: '伸港鄉', select: false, code: '509' },
        { distName: '員林市', select: false, code: '510' },
        { distName: '社頭鄉', select: false, code: '511' },
        { distName: '永靖鄉', select: false, code: '512' },
        { distName: '埔心鄉', select: false, code: '513' },
        { distName: '溪湖鎮', select: false, code: '514' },
        { distName: '大村鄉', select: false, code: '515' },
        { distName: '埔鹽鄉', select: false, code: '516' },
        { distName: '田中鎮', select: false, code: '520' },
        { distName: '北斗鎮', select: false, code: '521' },
        { distName: '田尾鄉', select: false, code: '522' },
        { distName: '埤頭鄉', select: false, code: '523' },
        { distName: '溪州鄉', select: false, code: '524' },
        { distName: '竹塘鄉', select: false, code: '525' },
        { distName: '二林鎮', select: false, code: '526' },
        { distName: '大城鄉', select: false, code: '527' },
        { distName: '芳苑鄉', select: false, code: '528' },
        { distName: '二水鄉', select: false, code: '530' },
      ],
    },
    {
      cityName: '南投縣',
      selectAll: false,
      district: [
        { distName: '南投市', select: false, code: '540' },
        { distName: '中寮鄉', select: false, code: '541' },
        { distName: '草屯鎮', select: false, code: '542' },
        { distName: '國姓鄉', select: false, code: '544' },
        { distName: '埔里鎮', select: false, code: '545' },
        { distName: '仁愛鄉', select: false, code: '546' },
        { distName: '名間鄉', select: false, code: '551' },
        { distName: '集集鎮', select: false, code: '552' },
        { distName: '水里鄉', select: false, code: '553' },
        { distName: '魚池鄉', select: false, code: '555' },
        { distName: '信義鄉', select: false, code: '556' },
        { distName: '竹山鎮', select: false, code: '557' },
        { distName: '鹿谷鄉', select: false, code: '558' },
      ],
    },
    {
      cityName: '嘉義市',
      selectAll: false,
      district: [
        { distName: '東區', select: false, code: '600' },
        { distName: '西區', select: false, code: '600' },
      ],
    },
    {
      cityName: '嘉義縣',
      selectAll: false,
      district: [
        { distName: '番路鄉', select: false, code: '602' },
        { distName: '梅山鄉', select: false, code: '603' },
        { distName: '竹崎鄉', select: false, code: '604' },
        { distName: '阿里山', select: false, code: '605' },
        { distName: '中埔鄉', select: false, code: '606' },
        { distName: '大埔鄉', select: false, code: '607' },
        { distName: '水上鄉', select: false, code: '608' },
        { distName: '鹿草鄉', select: false, code: '611' },
        { distName: '太保市', select: false, code: '612' },
        { distName: '朴子市', select: false, code: '613' },
        { distName: '東石鄉', select: false, code: '614' },
        { distName: '六腳鄉', select: false, code: '615' },
        { distName: '新港鄉', select: false, code: '616' },
        { distName: '民雄鄉', select: false, code: '621' },
        { distName: '大林鎮', select: false, code: '622' },
        { distName: '溪口鄉', select: false, code: '623' },
        { distName: '義竹鄉', select: false, code: '624' },
        { distName: '布袋鎮', select: false, code: '625' },
      ],
    },
    {
      cityName: '雲林縣',
      selectAll: false,
      district: [
        { distName: '斗南鎮', select: false, code: '630' },
        { distName: '大埤鄉', select: false, code: '631' },
        { distName: '虎尾鎮', select: false, code: '632' },
        { distName: '土庫鎮', select: false, code: '633' },
        { distName: '褒忠鄉', select: false, code: '634' },
        { distName: '東勢鄉', select: false, code: '635' },
        { distName: '台西鄉', select: false, code: '636' },
        { distName: '崙背鄉', select: false, code: '637' },
        { distName: '麥寮鄉', select: false, code: '638' },
        { distName: '斗六市', select: false, code: '640' },
        { distName: '林內鄉', select: false, code: '643' },
        { distName: '古坑鄉', select: false, code: '646' },
        { distName: '莿桐鄉', select: false, code: '647' },
        { distName: '西螺鎮', select: false, code: '648' },
        { distName: '二崙鄉', select: false, code: '649' },
        { distName: '北港鎮', select: false, code: '651' },
        { distName: '水林鄉', select: false, code: '652' },
        { distName: '口湖鄉', select: false, code: '653' },
        { distName: '四湖鄉', select: false, code: '654' },
        { distName: '元長鄉', select: false, code: '655' },
      ],
    },
    {
      cityName: '台南市',
      selectAll: false,
      district: [
        { distName: '中西區', select: false, code: '700' },
        { distName: '東區', select: false, code: '701' },
        { distName: '南區', select: false, code: '702' },
        { distName: '北區', select: false, code: '704' },
        { distName: '安平區', select: false, code: '708' },
        { distName: '安南區', select: false, code: '709' },
        { distName: '永康區', select: false, code: '710' },
        { distName: '歸仁區', select: false, code: '711' },
        { distName: '新化區', select: false, code: '712' },
        { distName: '左鎮區', select: false, code: '713' },
        { distName: '玉井區', select: false, code: '714' },
        { distName: '楠西區', select: false, code: '715' },
        { distName: '南化區', select: false, code: '716' },
        { distName: '仁德區', select: false, code: '717' },
        { distName: '關廟區', select: false, code: '718' },
        { distName: '龍崎區', select: false, code: '719' },
        { distName: '官田區', select: false, code: '720' },
        { distName: '麻豆區', select: false, code: '721' },
        { distName: '佳里區', select: false, code: '722' },
        { distName: '西港區', select: false, code: '723' },
        { distName: '七股區', select: false, code: '724' },
        { distName: '將軍區', select: false, code: '725' },
        { distName: '學甲區', select: false, code: '726' },
        { distName: '北門區', select: false, code: '727' },
        { distName: '新營區', select: false, code: '730' },
        { distName: '後壁區', select: false, code: '731' },
        { distName: '白河區', select: false, code: '732' },
        { distName: '東山區', select: false, code: '733' },
        { distName: '六甲區', select: false, code: '734' },
        { distName: '下營區', select: false, code: '735' },
        { distName: '柳營區', select: false, code: '736' },
        { distName: '鹽水區', select: false, code: '737' },
        { distName: '善化區', select: false, code: '741' },
        { distName: '大內區', select: false, code: '742' },
        { distName: '山上區', select: false, code: '743' },
        { distName: '新市區', select: false, code: '744' },
        { distName: '安定區', select: false, code: '745' },
      ],
    },
    {
      cityName: '高雄市',
      selectAll: false,
      district: [
        { distName: '新興區', select: false, code: '800' },
        { distName: '前金區', select: false, code: '801' },
        { distName: '苓雅區', select: false, code: '802' },
        { distName: '鹽埕區', select: false, code: '803' },
        { distName: '鼓山區', select: false, code: '804' },
        { distName: '旗津區', select: false, code: '805' },
        { distName: '前鎮區', select: false, code: '806' },
        { distName: '三民區', select: false, code: '807' },
        { distName: '楠梓區', select: false, code: '811' },
        { distName: '小港區', select: false, code: '812' },
        { distName: '左營區', select: false, code: '813' },
        { distName: '仁武區', select: false, code: '814' },
        { distName: '大社區', select: false, code: '815' },
        { distName: '東沙群島', select: false, code: '817' },
        { distName: '南沙群島', select: false, code: '819' },
        { distName: '岡山區', select: false, code: '820' },
        { distName: '路竹區', select: false, code: '821' },
        { distName: '阿蓮區', select: false, code: '822' },
        { distName: '田寮區', select: false, code: '823' },
        { distName: '燕巢區', select: false, code: '824' },
        { distName: '橋頭區', select: false, code: '825' },
        { distName: '梓官區', select: false, code: '826' },
        { distName: '彌陀區', select: false, code: '827' },
        { distName: '永安區', select: false, code: '828' },
        { distName: '湖內區', select: false, code: '829' },
        { distName: '鳳山區', select: false, code: '830' },
        { distName: '大寮區', select: false, code: '831' },
        { distName: '林園區', select: false, code: '832' },
        { distName: '鳥松區', select: false, code: '833' },
        { distName: '大樹區', select: false, code: '840' },
        { distName: '旗山區', select: false, code: '842' },
        { distName: '美濃區', select: false, code: '843' },
        { distName: '六龜區', select: false, code: '844' },
        { distName: '內門區', select: false, code: '845' },
        { distName: '杉林區', select: false, code: '846' },
        { distName: '甲仙區', select: false, code: '847' },
        { distName: '桃源區', select: false, code: '848' },
        { distName: '那瑪夏區', select: false, code: '849' },
        { distName: '茂林區', select: false, code: '851' },
        { distName: '茄萣區', select: false, code: '852' },
      ],
    },
    {
      cityName: '澎湖縣',
      selectAll: false,
      district: [
        { distName: '馬公市', select: false, code: '880' },
        { distName: '西嶼鄉', select: false, code: '881' },
        { distName: '望安鄉', select: false, code: '882' },
        { distName: '七美鄉', select: false, code: '883' },
        { distName: '白沙鄉', select: false, code: '884' },
        { distName: '湖西鄉', select: false, code: '885' },
      ],
    },
    {
      cityName: '金門縣',
      selectAll: false,
      district: [
        { distName: '金沙鎮', select: false, code: '890' },
        { distName: '金湖鎮', select: false, code: '891' },
        { distName: '金寧鄉', select: false, code: '892' },
        { distName: '金城鎮', select: false, code: '893' },
        { distName: '烈嶼鄉', select: false, code: '894' },
        { distName: '烏坵鄉', select: false, code: '896' },
      ],
    },
    {
      cityName: '屏東縣',
      selectAll: false,
      district: [
        { distName: '屏東市', select: false, code: '900' },
        { distName: '三地門鄉', select: false, code: '901' },
        { distName: '霧台鄉', select: false, code: '902' },
        { distName: '瑪家鄉', select: false, code: '903' },
        { distName: '九如鄉', select: false, code: '904' },
        { distName: '里港鄉', select: false, code: '905' },
        { distName: '高樹鄉', select: false, code: '906' },
        { distName: '鹽埔鄉', select: false, code: '907' },
        { distName: '長治鄉', select: false, code: '908' },
        { distName: '麟洛鄉', select: false, code: '909' },
        { distName: '竹田鄉', select: false, code: '911' },
        { distName: '內埔鄉', select: false, code: '912' },
        { distName: '萬丹鄉', select: false, code: '913' },
        { distName: '潮州鎮', select: false, code: '920' },
        { distName: '泰武鄉', select: false, code: '921' },
        { distName: '來義鄉', select: false, code: '922' },
        { distName: '萬巒鄉', select: false, code: '923' },
        { distName: '崁頂鄉', select: false, code: '924' },
        { distName: '新埤鄉', select: false, code: '925' },
        { distName: '南州鄉', select: false, code: '926' },
        { distName: '林邊鄉', select: false, code: '927' },
        { distName: '東港鎮', select: false, code: '928' },
        { distName: '琉球鄉', select: false, code: '929' },
        { distName: '佳冬鄉', select: false, code: '931' },
        { distName: '新園鄉', select: false, code: '932' },
        { distName: '枋寮鄉', select: false, code: '940' },
        { distName: '枋山鄉', select: false, code: '941' },
        { distName: '春日鄉', select: false, code: '942' },
        { distName: '獅子鄉', select: false, code: '943' },
        { distName: '車城鄉', select: false, code: '944' },
        { distName: '牡丹鄉', select: false, code: '945' },
        { distName: '恆春鎮', select: false, code: '946' },
        { distName: '滿州鄉', select: false, code: '947' },
      ],
    },
    {
      cityName: '台東縣',
      selectAll: false,
      district: [
        { distName: '台東市', select: false, code: '950' },
        { distName: '綠島鄉', select: false, code: '951' },
        { distName: '蘭嶼鄉', select: false, code: '952' },
        { distName: '延平鄉', select: false, code: '953' },
        { distName: '卑南鄉', select: false, code: '954' },
        { distName: '鹿野鄉', select: false, code: '955' },
        { distName: '關山鎮', select: false, code: '956' },
        { distName: '海端鄉', select: false, code: '957' },
        { distName: '池上鄉', select: false, code: '958' },
        { distName: '東河鄉', select: false, code: '959' },
        { distName: '成功鎮', select: false, code: '961' },
        { distName: '長濱鄉', select: false, code: '962' },
        { distName: '太麻里', select: false, code: '963' },
        { distName: '金峰鄉', select: false, code: '964' },
        { distName: '大武鄉', select: false, code: '965' },
        { distName: '達仁鄉', select: false, code: '966' },
      ],
    },
    {
      cityName: '花蓮縣',
      selectAll: false,
      district: [
        { distName: '花蓮市', select: false, code: '970' },
        { distName: '新城鄉', select: false, code: '971' },
        { distName: '秀林鄉', select: false, code: '972' },
        { distName: '吉安鄉', select: false, code: '973' },
        { distName: '壽豐鄉', select: false, code: '974' },
        { distName: '鳳林鎮', select: false, code: '975' },
        { distName: '光復鄉', select: false, code: '976' },
        { distName: '豐濱鄉', select: false, code: '977' },
        { distName: '瑞穗鄉', select: false, code: '978' },
        { distName: '萬榮鄉', select: false, code: '979' },
        { distName: '玉里鎮', select: false, code: '981' },
        { distName: '卓溪鄉', select: false, code: '982' },
        { distName: '富里鄉', select: false, code: '983' },
      ],
    },
    {
      cityName: '連江縣',
      selectAll: false,
      district: [
        { distName: '南竿鄉', select: false, code: '209' },
        { distName: '北竿鄉', select: false, code: '210' },
        { distName: '莒光鄉', select: false, code: '211' },
        { distName: '東引鄉', select: false, code: '212' },
      ],
    },
  ],
};
export default webData;
